// Code generated by cdpgen. DO NOT EDIT.

package runtime

import (
	"encoding/json"

	"github.com/mafredri/cdp/rpcc"
)

// ExecutionContextCreatedClient receives ExecutionContextCreated events.
type ExecutionContextCreatedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*ExecutionContextCreatedReply, error)
	rpcc.Stream
}

// ExecutionContextCreatedReply issued when new execution context is created.
type ExecutionContextCreatedReply struct {
	Context ExecutionContextDescription `json:"context"` // A newly created execution context.
}

// ExecutionContextDestroyedClient receives ExecutionContextDestroyed events.
type ExecutionContextDestroyedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*ExecutionContextDestroyedReply, error)
	rpcc.Stream
}

// ExecutionContextDestroyedReply issued when execution context is destroyed.
type ExecutionContextDestroyedReply struct {
	ExecutionContextID ExecutionContextID `json:"executionContextId"` // Id of the destroyed context
}

// ExecutionContextsClearedClient receives ExecutionContextsCleared events.
type ExecutionContextsClearedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*ExecutionContextsClearedReply, error)
	rpcc.Stream
}

// ExecutionContextsClearedReply issued when all executionContexts were cleared in browser
type ExecutionContextsClearedReply struct{}

// ExceptionThrownClient receives ExceptionThrown events.
type ExceptionThrownClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*ExceptionThrownReply, error)
	rpcc.Stream
}

// ExceptionThrownReply issued when exception was thrown and unhandled.
type ExceptionThrownReply struct {
	Timestamp        Timestamp        `json:"timestamp"`        // Timestamp of the exception.
	ExceptionDetails ExceptionDetails `json:"exceptionDetails"` //
}

// ExceptionRevokedClient receives ExceptionRevoked events.
type ExceptionRevokedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*ExceptionRevokedReply, error)
	rpcc.Stream
}

// ExceptionRevokedReply issued when unhandled exception was revoked.
type ExceptionRevokedReply struct {
	Reason      string `json:"reason"`      // Reason describing why exception was revoked.
	ExceptionID int    `json:"exceptionId"` // The id of revoked exception, as reported in exceptionUnhandled.
}

// ConsoleAPICalledClient receives ConsoleAPICalled events.
type ConsoleAPICalledClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*ConsoleAPICalledReply, error)
	rpcc.Stream
}

// ConsoleAPICalledReply issued when console API was called.
type ConsoleAPICalledReply struct {
	Type               string             `json:"type"`                 // Type of the call.
	Args               []RemoteObject     `json:"args"`                 // Call arguments.
	ExecutionContextID ExecutionContextID `json:"executionContextId"`   // Identifier of the context where the call was made.
	Timestamp          Timestamp          `json:"timestamp"`            // Call timestamp.
	StackTrace         *StackTrace        `json:"stackTrace,omitempty"` // Stack trace captured when the call was made.
	Context            *string            `json:"context,omitempty"`    // Console context descriptor for calls on non-default console context (not console.*): 'anonymous#unique-logger-id' for call on unnamed context, 'name#unique-logger-id' for call on named context.
}

// InspectRequestedClient receives InspectRequested events.
type InspectRequestedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*InspectRequestedReply, error)
	rpcc.Stream
}

// InspectRequestedReply issued when object should be inspected (for example, as a result of inspect() command line API call).
type InspectRequestedReply struct {
	Object RemoteObject    `json:"object"` //
	Hints  json.RawMessage `json:"hints"`  //
}
