// Code generated by cdpgen. DO NOT EDIT.

package emulation

import (
	"github.com/mafredri/cdp/rpcc"
)

// VirtualTimeBudgetExpiredClient receives VirtualTimeBudgetExpired events.
type VirtualTimeBudgetExpiredClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*VirtualTimeBudgetExpiredReply, error)
	rpcc.Stream
}

// VirtualTimeBudgetExpiredReply notification sent after the virual time budget for the current VirtualTimePolicy has run out.
type VirtualTimeBudgetExpiredReply struct{}
