// Code generated by cdpgen. DO NOT EDIT.

package tethering

import (
	"github.com/mafredri/cdp/rpcc"
)

// AcceptedClient receives Accepted events.
type AcceptedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*AcceptedReply, error)
	rpcc.Stream
}

// AcceptedReply informs that port was successfully bound and got a specified connection id.
type AcceptedReply struct {
	Port         int    `json:"port"`         // Port number that was successfully bound.
	ConnectionID string `json:"connectionId"` // Connection id to be used.
}
