// Code generated by cdpgen. DO NOT EDIT.

package css

import (
	"github.com/mafredri/cdp/rpcc"
)

// MediaQueryResultChangedClient receives MediaQueryResultChanged events.
type MediaQueryResultChangedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*MediaQueryResultChangedReply, error)
	rpcc.Stream
}

// MediaQueryResultChangedReply fires whenever a MediaQuery result changes (for example, after a browser window has been resized.) The current implementation considers only viewport-dependent media features.
type MediaQueryResultChangedReply struct{}

// FontsUpdatedClient receives FontsUpdated events.
type FontsUpdatedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*FontsUpdatedReply, error)
	rpcc.Stream
}

// FontsUpdatedReply fires whenever a web font gets loaded.
type FontsUpdatedReply struct{}

// StyleSheetChangedClient receives StyleSheetChanged events.
type StyleSheetChangedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*StyleSheetChangedReply, error)
	rpcc.Stream
}

// StyleSheetChangedReply fired whenever a stylesheet is changed as a result of the client operation.
type StyleSheetChangedReply struct {
	StyleSheetID StyleSheetID `json:"styleSheetId"` //
}

// StyleSheetAddedClient receives StyleSheetAdded events.
type StyleSheetAddedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*StyleSheetAddedReply, error)
	rpcc.Stream
}

// StyleSheetAddedReply fired whenever an active document stylesheet is added.
type StyleSheetAddedReply struct {
	Header StyleSheetHeader `json:"header"` // Added stylesheet metainfo.
}

// StyleSheetRemovedClient receives StyleSheetRemoved events.
type StyleSheetRemovedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*StyleSheetRemovedReply, error)
	rpcc.Stream
}

// StyleSheetRemovedReply fired whenever an active document stylesheet is removed.
type StyleSheetRemovedReply struct {
	StyleSheetID StyleSheetID `json:"styleSheetId"` // Identifier of the removed stylesheet.
}
