// Code generated by cdpgen. DO NOT EDIT.

package inspector

import (
	"github.com/mafredri/cdp/rpcc"
)

// DetachedClient receives Detached events.
type DetachedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*DetachedReply, error)
	rpcc.Stream
}

// DetachedReply fired when remote debugging connection is about to be terminated. Contains detach reason.
type DetachedReply struct {
	Reason string `json:"reason"` // The reason why connection has been terminated.
}

// TargetCrashedClient receives TargetCrashed events.
type TargetCrashedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*TargetCrashedReply, error)
	rpcc.Stream
}

// TargetCrashedReply fired when debugging target has crashed
type TargetCrashedReply struct{}
