// Code generated by cdpgen. DO NOT EDIT.

package dom

import (
	"github.com/mafredri/cdp/rpcc"
)

// DocumentUpdatedClient receives DocumentUpdated events.
type DocumentUpdatedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*DocumentUpdatedReply, error)
	rpcc.Stream
}

// DocumentUpdatedReply fired when Document has been totally updated. Node ids are no longer valid.
type DocumentUpdatedReply struct{}

// SetChildNodesClient receives SetChildNodes events.
type SetChildNodesClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*SetChildNodesReply, error)
	rpcc.Stream
}

// SetChildNodesReply fired when backend wants to provide client with the missing DOM structure. This happens upon most of the calls requesting node ids.
type SetChildNodesReply struct {
	ParentID NodeID `json:"parentId"` // Parent node id to populate with children.
	Nodes    []Node `json:"nodes"`    // Child nodes array.
}

// AttributeModifiedClient receives AttributeModified events.
type AttributeModifiedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*AttributeModifiedReply, error)
	rpcc.Stream
}

// AttributeModifiedReply fired when Element's attribute is modified.
type AttributeModifiedReply struct {
	NodeID NodeID `json:"nodeId"` // Id of the node that has changed.
	Name   string `json:"name"`   // Attribute name.
	Value  string `json:"value"`  // Attribute value.
}

// AttributeRemovedClient receives AttributeRemoved events.
type AttributeRemovedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*AttributeRemovedReply, error)
	rpcc.Stream
}

// AttributeRemovedReply fired when Element's attribute is removed.
type AttributeRemovedReply struct {
	NodeID NodeID `json:"nodeId"` // Id of the node that has changed.
	Name   string `json:"name"`   // A ttribute name.
}

// InlineStyleInvalidatedClient receives InlineStyleInvalidated events.
type InlineStyleInvalidatedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*InlineStyleInvalidatedReply, error)
	rpcc.Stream
}

// InlineStyleInvalidatedReply fired when Element's inline style is modified via a CSS property modification.
type InlineStyleInvalidatedReply struct {
	NodeIDs []NodeID `json:"nodeIds"` // Ids of the nodes for which the inline styles have been invalidated.
}

// CharacterDataModifiedClient receives CharacterDataModified events.
type CharacterDataModifiedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*CharacterDataModifiedReply, error)
	rpcc.Stream
}

// CharacterDataModifiedReply mirrors DOMCharacterDataModified event.
type CharacterDataModifiedReply struct {
	NodeID        NodeID `json:"nodeId"`        // Id of the node that has changed.
	CharacterData string `json:"characterData"` // New text value.
}

// ChildNodeCountUpdatedClient receives ChildNodeCountUpdated events.
type ChildNodeCountUpdatedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*ChildNodeCountUpdatedReply, error)
	rpcc.Stream
}

// ChildNodeCountUpdatedReply fired when Container's child node count has changed.
type ChildNodeCountUpdatedReply struct {
	NodeID         NodeID `json:"nodeId"`         // Id of the node that has changed.
	ChildNodeCount int    `json:"childNodeCount"` // New node count.
}

// ChildNodeInsertedClient receives ChildNodeInserted events.
type ChildNodeInsertedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*ChildNodeInsertedReply, error)
	rpcc.Stream
}

// ChildNodeInsertedReply mirrors DOMNodeInserted event.
type ChildNodeInsertedReply struct {
	ParentNodeID   NodeID `json:"parentNodeId"`   // Id of the node that has changed.
	PreviousNodeID NodeID `json:"previousNodeId"` // If of the previous siblint.
	Node           Node   `json:"node"`           // Inserted node data.
}

// ChildNodeRemovedClient receives ChildNodeRemoved events.
type ChildNodeRemovedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*ChildNodeRemovedReply, error)
	rpcc.Stream
}

// ChildNodeRemovedReply mirrors DOMNodeRemoved event.
type ChildNodeRemovedReply struct {
	ParentNodeID NodeID `json:"parentNodeId"` // Parent id.
	NodeID       NodeID `json:"nodeId"`       // Id of the node that has been removed.
}

// ShadowRootPushedClient receives ShadowRootPushed events.
type ShadowRootPushedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*ShadowRootPushedReply, error)
	rpcc.Stream
}

// ShadowRootPushedReply called when shadow root is pushed into the element.
type ShadowRootPushedReply struct {
	HostID NodeID `json:"hostId"` // Host element id.
	Root   Node   `json:"root"`   // Shadow root.
}

// ShadowRootPoppedClient receives ShadowRootPopped events.
type ShadowRootPoppedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*ShadowRootPoppedReply, error)
	rpcc.Stream
}

// ShadowRootPoppedReply called when shadow root is popped from the element.
type ShadowRootPoppedReply struct {
	HostID NodeID `json:"hostId"` // Host element id.
	RootID NodeID `json:"rootId"` // Shadow root id.
}

// PseudoElementAddedClient receives PseudoElementAdded events.
type PseudoElementAddedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*PseudoElementAddedReply, error)
	rpcc.Stream
}

// PseudoElementAddedReply called when a pseudo element is added to an element.
type PseudoElementAddedReply struct {
	ParentID      NodeID `json:"parentId"`      // Pseudo element's parent element id.
	PseudoElement Node   `json:"pseudoElement"` // The added pseudo element.
}

// PseudoElementRemovedClient receives PseudoElementRemoved events.
type PseudoElementRemovedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*PseudoElementRemovedReply, error)
	rpcc.Stream
}

// PseudoElementRemovedReply called when a pseudo element is removed from an element.
type PseudoElementRemovedReply struct {
	ParentID        NodeID `json:"parentId"`        // Pseudo element's parent element id.
	PseudoElementID NodeID `json:"pseudoElementId"` // The removed pseudo element id.
}

// DistributedNodesUpdatedClient receives DistributedNodesUpdated events.
type DistributedNodesUpdatedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*DistributedNodesUpdatedReply, error)
	rpcc.Stream
}

// DistributedNodesUpdatedReply called when distribution is changed.
type DistributedNodesUpdatedReply struct {
	InsertionPointID NodeID        `json:"insertionPointId"` // Insertion point where distributed nodes were updated.
	DistributedNodes []BackendNode `json:"distributedNodes"` // Distributed nodes for given insertion point.
}
