// Code generated by cdpgen. DO NOT EDIT.

package applicationcache

import (
	"github.com/mafredri/cdp/protocol/page"
	"github.com/mafredri/cdp/rpcc"
)

// StatusUpdatedClient receives ApplicationCacheStatusUpdated events.
type StatusUpdatedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*StatusUpdatedReply, error)
	rpcc.Stream
}

// StatusUpdatedReply
type StatusUpdatedReply struct {
	FrameID     page.FrameID `json:"frameId"`     // Identifier of the frame containing document whose application cache updated status.
	ManifestURL string       `json:"manifestURL"` // Manifest URL.
	Status      int          `json:"status"`      // Updated application cache status.
}

// NetworkStateUpdatedClient receives NetworkStateUpdated events.
type NetworkStateUpdatedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*NetworkStateUpdatedReply, error)
	rpcc.Stream
}

// NetworkStateUpdatedReply
type NetworkStateUpdatedReply struct {
	IsNowOnline bool `json:"isNowOnline"` //
}
