// Code generated by cdpgen. DO NOT EDIT.

package overlay

import (
	"github.com/mafredri/cdp/protocol/dom"
	"github.com/mafredri/cdp/rpcc"
)

// NodeHighlightRequestedClient receives NodeHighlightRequested events.
type NodeHighlightRequestedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*NodeHighlightRequestedReply, error)
	rpcc.Stream
}

// NodeHighlightRequestedReply fired when the node should be highlighted. This happens after call to setInspectMode.
type NodeHighlightRequestedReply struct {
	NodeID dom.NodeID `json:"nodeId"` //
}

// InspectNodeRequestedClient receives InspectNodeRequested events.
type InspectNodeRequestedClient interface {
	// Recv calls RecvMsg on rpcc.Stream, blocks until the event is
	// triggered, context canceled or connection closed.
	Recv() (*InspectNodeRequestedReply, error)
	rpcc.Stream
}

// InspectNodeRequestedReply fired when the node should be inspected. This happens after call to setInspectMode or when user manually inspects an element.
type InspectNodeRequestedReply struct {
	BackendNodeID dom.BackendNodeID `json:"backendNodeId"` // Id of the node to inspect.
}
